version: "3.9"

services:
  orders-service:
    build:
      context: ./Orders
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
        - app-network
    depends_on:
      - postgres
      - rabbitmq

#  products-service:
#    build:
#      context: ./products-service
#      dockerfile: Dockerfile
#    ports:
#      - "8082:8080"
#    depends_on:
#      - postgres

#  users-service:
#    build:
#      context: ./users-service
#      dockerfile: Dockerfile
#    ports:
#      - "8083:8080"
#    depends_on:
#      - postgres

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
        - app-network

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_db
    ports:
      - "5432:5432"
    networks:
        - app-network

  adminer:
    image: adminer
    ports:
      - "8080:8080"
networks:
  app-network:
    driver: bridge