version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq-project
    ports:
      - "5672:5672" # RabbitMQ default port
      - "15672:15672" # RabbitMQ management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest