version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  consumer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rabbitmq-consumer
    ports:
      - "8081:8080"
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_PROFILES_ACTIVE: routing,receiver
    depends_on:
      - rabbitmq

  producer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rabbitmq-producer
    ports:
      - "8082:8080"
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_PROFILES_ACTIVE: routing,sender
    depends_on:
      - rabbitmq